spring.application.name=kolok

discord.token=${DISCORD_BOT_TOKEN:#{'TOKEN_NOT_SET'}}
discord.planning.channel=${DISCORD_PLANNING_CHANNEL_ID:#{'CHANNEL_ID_NOT_SET'}}
discord.guild-id=${DISCORD_GUILD_ID:#{'GUILD_ID_NOT_SET'}}

persistense.json.path=${JSON_DIR_PATH:#{'data'}}